<?php

/**
 * Implements hook_entity_info().
 */
function ftep_project_entity_info() {
    $info = array (
        'ftep_project' => array (
            'label' => t ( 'Ftep Project' ),
            'base table' => 'ftep_project',
            'entity keys' => array (
                'id' => 'pid',
                'label' => 'name' 
            ),
            'entity class' => 'FtepProjects',  // 'Entity',
            'controller class' => 'FtepProjectsController',
            'access callback' => 'ftep_projects_access_callback',
            'module' => 'ftep_project',
            'fieldable' => false,
            'admin ui' => array (
                'path' => 'admin/ftep/projects',
                'file' => 'ftep_project.admin.inc',
                'type' => MENU_NORMAL_ITEM,
                'controller class' => 'FtepProjectUIController'
            ),
        )
    ) ;
    return $info;
}

/**
 * Implements hook_menu().
 */
function ftep_project_menu() {
	$items = array ();

	$items ['projects'] = array (
			'title' => 'Projects',
			'page callback' => 'ftep_project_projects',
			'access arguments' => array (
					'administer ftep_projects entities'
			)
	);
	return $items;
}


/**
 * Projects access callback.
 */
function ftep_projects_access_callback() {
	if (user_is_anonymous () && ! user_access ( 'administer ftep_projects entities' )) {
		return FALSE;
	} else {
		return TRUE;
	}
}

function ftep_project_projects() {
	$databaskets = entity_load ( 'ftep_project', array ( 1, 2, 3) );
	// Listing entities
	$list = entity_view ( 'ftep_project', $databaskets );

	$output = array ();
	if (! array_key_exists ( "ftep_project", $list )) {
		return $output;
	}
	foreach ( $list ['ftep_project'] as $databasket ) {
		$output [] = drupal_render ( $databasket );
	}

	return implode ( $output );
}



function ftep_project_permission() {
    return array(
            'administer ftep_project entities' => array('title'=> t("Administer Ftep Projects"), "description" => t("Administer Ftep Projects") ),
            'create ftep_project entities' => array('title'=> t("Create Ftep Projects entities"), "description" => t("Create Ftep Projects") ),
            'edit any ftep_project entity' => array('title'=> t("Edit any Ftep Projects"), "description" => t("Edit any Ftep Projects") ),
            'edit own ftep_project entities' => array('title'=> t("Edit own Ftep Projects"), "description" => t("Edit own Ftep Projects") ),
            'view any ftep_project entity' => array('title'=> t("View any Ftep Projects"), "description" => t("View any Ftep Projects") ),
            'view own ftep_project entities' => array('title'=> t("View own Ftep Projects"), "description" => t("View own Ftep Projects") ),
    );
}

/**
 * Lawmakers custom entity class.
 */
class FtepProjects extends Entity {
	/**
	 * Override defaultUri().
	 */
	protected function defaultUri() {
		return array (
				'path' => 'projects/' . $this->identifier ()
		);
	}
}
