<?php

/**
 * Implements hook_entity_info().
 */
function ftep_datasource_entity_info() {
    $info = array (
        'ftep_datasource' => array (
            'label' => t ( 'Ftep Datasource' ),
            'base table' => 'ftep_datasource',
            'entity keys' => array (
                'id' => 'id',
                'label' => 'name'
            ),					
            'entity class' => 'FtepDatasources',
            'controller class' => 'FtepDatasourcesController',
            'access callback' => 'ftep_datasources_access_callback',
            'module' => 'ftep_datasource',
            'fieldable' => TRUE,
            'admin ui' => array (
                'path' => 'admin/ftep/datasources',
                'file' => 'ftep_datasource.admin.inc',
                'type' => MENU_NORMAL_ITEM,
                'controller class' => 'FtepDatasourceUIController' 
            ),
        ) 
    );
    return $info;
}
/**
 * Implements hook_menu().
 */
function ftep_datasource_menu() {
	$items = array ();

	$items ['datasources'] = array (
			'title' => 'Datasources',
			'page callback' => 'ftep_datasource_datasources',
			'access arguments' => array (
					'administer ftep_datasource entities'
			)
	);
	return $items;
}
function ftep_datasource_permission() {
    return array(
            'administer ftep_datasource entities' => array('title'=> t("Administer Ftep Datasources"), "description" => t("Administer Ftep Datasources") ),
            'create ftep_datasource entities' => array('title'=> t("Create Ftep Datasources entities"), "description" => t("Create Ftep Datasources") ),
            'edit any ftep_datasource entity' => array('title'=> t("Edit any Ftep Datasources"), "description" => t("Edit any Ftep Datasources") ),
            'edit own ftep_datasource entities' => array('title'=> t("Edit own Ftep Datasources"), "description" => t("Edit own Ftep Datasources") ),
            'view any ftep_datasource entity' => array('title'=> t("View any Ftep Datasources"), "description" => t("View any Ftep Datasources") ),
            'view own ftep_datasource entities' => array('title'=> t("View own Ftep Datasources"), "description" => t("View own Ftep Datasources") ),
    );
}


/**
 * Datasource access callback.
 */
function ftep_datasources_access_callback() {
	if (user_is_anonymous () && ! user_access ( 'administer ftep_datasources entities' )) {
		return FALSE;
	} else {
		return TRUE;
	}
}
function ftep_datasource_datasources() {
	$databaskets = entity_load ( 'ftep_datasource', array ( 1, 2, 3) );
	// Listing entities
	$list = entity_view ( 'ftep_datasource', $databaskets );

	$output = array ();
	if (! array_key_exists ( "ftep_datasource", $list )) {
		return $output;
	}
	foreach ( $list ['ftep_datasource'] as $databasket ) {
		$output [] = drupal_render ( $databasket );
	}

	return implode ( $output );
}

/**
 * View for /lawmakers/<lawmakers_id> page.
 */
function datasources_view_entity($datasource) {
	$fullname = $datasource->name . ' ' . $datasource->description;
	drupal_set_title ( $fullname );
	// Path not entity.
	// $lawmakers_output = theme('lawmakers_full', array('lawmakers' => $lawmakers));
	return $lawmakers_output;
}

/**
 * Lawmakers custom entity class.
 */
class FtepDatasources extends Entity {
	/**
	 * Override defaultUri().
	 */
	protected function defaultUri() {
		return array (
				'path' => 'datasources/' . $this->identifier () 
		);
	}
}
