package com.cgi.eoss.ftep.model;

public enum FtepFileType {
    /**
     * <p>User-managed reference data file.</p>
     */

    REFERENCE_DATA,
    /**
     * <p>Output product generated by an F-TEP service.</p>
     */

    OUTPUT_PRODUCT,

    /**
     * <p>External data product reference.</p>
     */
    EXTERNAL_PRODUCT;
}
