---
catalogue:
  title: 'Catalogue'
  type: 'catalogue'
  allowed:
    values:
      - value: 'SATELLITE'
        title: 'Satellite'
        description: 'Satellite products'
      - value: 'REF_DATA'
        title: 'Reference'
        description: 'User-uploaded reference and in situ data'
      - value: 'FTEP_PRODUCTS'
        title: 'F-TEP Products'
        description: 'All pre-processed data'

owner:
  title: 'Owner'
  type: 'text'
  onlyIf:
    'catalogue':
      - 'REF_DATA'
      - 'FTEP_PRODUCTS'

mission:
  title: 'Mission'
  type: 'select'
  defaultValue: 'sentinel2'
  allowed:
    values:
      - value: 'sentinel1'
        title: 'Sentinel-1'
      - value: 'sentinel2'
        title: 'Sentinel-2'
      - value: 'sentinel3'
        title: 'Sentinel-3'
      - value: 'sentinel5'
        title: 'Sentinel-5P'
      - value: 'landsat'
        title: 'Landsat'
  onlyIf:
    'catalogue':
      - 'SATELLITE'

productDate:
  title: 'Product date'
  type: 'daterange'
  description: 'UTC'
  defaultValue:
    - '-3'
    - '0'

aoi:
  title: 'AOI'
  type: 'polygon'
  description: 'WKT polygon'

identifier:
  title: 'Identifier'
  type: 'text'
  description: 'Product identifier string'

platform:
  title: 'Platform'
  type: 'select'
  defaultValue: 'Landsat-8'
  allowed:
    values:
      - value: 'Landsat-5'
        title: 'Landsat-5'
        onlyIf:
          'mission':
            - 'landsat'
      - value: 'Landsat-7'
        title: 'Landsat-7'
        onlyIf:
          'mission':
            - 'landsat'
      - value: 'Landsat-8'
        title: 'Landsat-8'
        onlyIf:
          'mission':
            - 'landsat'
  onlyIf:
    'mission':
      - 'landsat'

maxCloudCover:
  title: 'Cloud Coverage'
  type: 'int'
  description: 'Maximum (%)'
  defaultValue: 10
  allowed:
    min: 0
    max: 100
  onlyIf:
    'mission':
      - 'sentinel2'
      - 'landsat'

s1ProcessingLevel:
  title: 'Processing level (S-1)'
  type: 'select'
  defaultValue: '1'
  allowed:
    values:
      - value: '1'
        title: 'Level 1'
      - value: '2'
        title: 'Level 2'
  onlyIf:
    'mission':
      - 'sentinel1'

s2ProcessingLevel:
  title: 'Processing level (S-2)'
  type: 'select'
  defaultValue: '1C'
  allowed:
    values:
      - value: '1C'
        title: 'Level 1'
      - value: '2A'
        title: 'Level 2A'
      - value: '2AP'
        title: 'Level 2AP'
  onlyIf:
    'mission':
      - 'sentinel2'

s3ProcessingLevel:
  title: 'Processing level (S-3)'
  type: 'select'
  defaultValue: '1'
  allowed:
    values:
      - value: '1'
        title: 'Level 1'
      - value: '2'
        title: 'Level 2'
  onlyIf:
    'mission':
      - 'sentinel3'

landsatProcessingLevel:
  title: 'Processing level (Landsat)'
  type: 'select'
  defaultValue: '1GT'
  allowed:
    values:
      - value: '1G'
        title: '1G'
        onlyIf:
          'platform':
            - 'Landsat-5'
            - 'Landsat-7'
            - 'Landsat-8'
      - value: '1T'
        title: '1T'
        onlyIf:
          'platform':
            - 'Landsat-5'
            - 'Landsat-7'
            - 'Landsat-8'
      - value: '1GT'
        title: '1GT'
        onlyIf:
          'platform':
            - 'Landsat-7'
            - 'Landsat-8'
  onlyIf:
    'mission':
      - 'landsat'

s1ProductType:
  title: 'Product type'
  type: 'select'
  defaultValue: 'GRD'
  allowed:
    values:
      - value: 'GRD'
        title: 'GRD'
      - value: 'SLC'
        title: 'SLC'
      - value: 'OCN'
        title: 'OCN'
      - value: 'RAW'
        title: 'RAW'
  onlyIf:
    'mission':
      - 'sentinel1'

orbitDirection:
  title: 'Orbit direction'
  type: 'select'
  defaultValue: 'ASCENDING'
  allowed:
    values:
      - value: 'ASCENDING'
        title: 'ASCENDING'
      - value: 'DESCENDING'
        title: 'DESCENDING'
  onlyIf:
    'mission':
      - 'sentinel1'
      - 'sentinel3'

s1Platform:
  title: 'S-1 Platform'
  type: 'select'
  allowed:
    values:
      - value: 'S1A'
        title: 'S1A'
      - value: 'S1B'
        title: 'S1B'
  onlyIf:
    'mission':
      - 'sentinel1'
