package com.cgi.eoss.ftep;

import com.cgi.eoss.ftep.wps.StandaloneOrchestrator;
import com.cgi.eoss.ftep.wps.FtepServicesClient;
import com.google.common.collect.ImmutableMultimap;
import com.google.common.collect.Multimap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;

/**
 * <p>An example class as would be generated by the JavaWpsServiceWriter in f-tep-zoowrapper.</p>
 */
public final class ExampleWpsStub {
    private static final Logger LOG = LoggerFactory.getLogger(ExampleWpsStub.class);
    private static final String SERVER_NAME = "f-tep-standalone-test";

    public static int StandaloneWpsStub(HashMap conf, HashMap inputs, HashMap outputs) {
        try (StandaloneOrchestrator inProcessRpc = new StandaloneOrchestrator(SERVER_NAME)) {
            FtepServicesClient client = new FtepServicesClient(inProcessRpc.getChannelBuilder());

            LOG.info("Calling service ExampleWpsStub");

            Multimap<String, String> serviceOutputs = client.launchService(
                    "testJob",
                    "testUser",
                    "testService",
                    ImmutableMultimap.of("input", "ftep://INPUT_FILE",
                            "timeout", "1"));

            outputs.putAll(serviceOutputs.asMap());

            return 3;
        } catch (Exception e) {
            LOG.error("WPS service execution did not complete successfully", e);
            return 4;
        }
    }
}
