package com.cgi.eoss.ftep;

import com.cgi.eoss.ftep.wps.StandaloneOrchestrator;
import com.cgi.eoss.ftep.wps.WpsServicesClient;
import com.google.common.collect.ImmutableList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;

/**
 * <p>An example class as would be generated by the JavaWpsServiceWriter in f-tep-zoowrapper.</p>
 */
public final class StandaloneWpsStub {
    private static final Logger LOG = LoggerFactory.getLogger(StandaloneWpsStub.class);
    private static final String SERVER_NAME = "f-tep-standalone-test";

    public static int StandaloneWpsStub(HashMap conf, HashMap inputs, HashMap outputs) {
        try (StandaloneOrchestrator inProcessRpc = new StandaloneOrchestrator(SERVER_NAME)) {
            WpsServicesClient client = new WpsServicesClient(inProcessRpc.getChannelBuilder());

            LOG.info("Calling service StandaloneWpsStub");

            String outputUrl = client.launchApplication(
                    "testJob",
                    "testApp",
                    "testUser",
                    "testService",
                    ImmutableList.of("ftep://INPUT_FILE"),
                    1);

            return 3;
        } catch (Exception e) {
            LOG.error("WPS service execution did not complete successfully", e);
            return 4;
        }
    }
}
