<?php

/**
 * Implements hook_entity_info().
 */
function ftep_file_entity_info() {
    $info = array (
        'ftep_file' => array (
            'label' => t ( 'Ftep File' ),
            'base table' => 'ftep_file',
            'entity keys' => array (
                'id' => 'fid',
                'label' => 'name'
            ),					
            'entity class' => 'FtepFiles',
            'controller class' => 'FtepFilesController',
            'access callback' => 'ftep_files_access_callback',
            'module' => 'ftep_file',
            'fieldable' => false,
            'admin ui' => array (
                'path' => 'admin/ftep/files',
                'file' => 'ftep_file.admin.inc',
                'type' => MENU_NORMAL_ITEM,
                'controller class' => 'FtepFileUIController' 
            ),
        ) 
    );
    return $info;
}

/**
 * Implements hook_menu().
 */
function ftep_file_menu() {
	$items = array ();

	$items ['files'] = array (
			'title' => 'Files',
			'page callback' => 'ftep_file_files',
			'access arguments' => array (
					'administer ftep_file entities'
			)
	);
	return $items;
}

/**
 * File access callback.
 */
function ftep_files_access_callback() {
	if (user_is_anonymous () && ! user_access ( 'administer ftep_files entities' )) {
		return FALSE;
	} else {
		return TRUE;
	}
}

function ftep_file_files() {
	$files = entity_load ( 'ftep_file', array ( 1, 2, 3) );
	// Listing entities
	$list = entity_view ( 'ftep_file', $files );

	$output = array ();
	if (! array_key_exists ( "ftep_file", $list )) {
		return $output;
	}
	foreach ( $list ['ftep_file'] as $file ) {
		$output [] = drupal_render ( $file );
	}

	return implode ( $output );
}

/**
 * View for /lawmakers/<lawmakers_id> page.
 */
function files_view_entity($file) {
	$fullname = $file->name . ' ' . $file->description;
	drupal_set_title ( $fullname );
	// Path not entity.
	// $lawmakers_output = theme('lawmakers_full', array('lawmakers' => $lawmakers));
	return $lawmakers_output;
}



function ftep_file_permission() {
    return array(
            'administer ftep_file entities' => array('title'=> t("Administer Ftep Files"), "description" => t("Administer Ftep Files") ),
            'create ftep_file entities' => array('title'=> t("Create Ftep Files entities"), "description" => t("Create Ftep Files") ),
            'edit any ftep_file entity' => array('title'=> t("Edit any Ftep Files"), "description" => t("Edit any Ftep Files") ),
            'edit own ftep_file entities' => array('title'=> t("Edit own Ftep Files"), "description" => t("Edit own Ftep Files") ),
            'view any ftep_file entity' => array('title'=> t("View any Ftep Files"), "description" => t("View any Ftep Files") ),
            'view own ftep_file entities' => array('title'=> t("View own Ftep Files"), "description" => t("View own Ftep Files") ),
    );
}


/**
 * Lawmakers custom entity class.
 */
class FtepFiles extends Entity {
	/**
	 * Override defaultUri().
	 */
	protected function defaultUri() {
		return array (
				'path' => 'files/' . $this->identifier () 
		);
	}
}
