-- Add data source policies

CREATE TYPE FTEP_DATA_SOURCES_POLICY AS ENUM ('CACHE', 'MIRROR', 'REMOTE_ONLY');

CREATE OR REPLACE FUNCTION ftep_data_sources_policy_cast(VARCHAR)
  RETURNS FTEP_DATA_SOURCES_POLICY AS $$ SELECT ('' || $1) :: FTEP_DATA_SOURCES_POLICY $$ LANGUAGE SQL IMMUTABLE;
CREATE CAST ( VARCHAR AS FTEP_DATA_SOURCES_POLICY )
WITH FUNCTION ftep_data_sources_policy_cast(VARCHAR) AS IMPLICIT;

ALTER TABLE ftep_data_sources
  ADD COLUMN policy FTEP_DATA_SOURCES_POLICY NOT NULL DEFAULT 'CACHE';
