ALTER TABLE ftep_users
    ADD COLUMN IF NOT EXISTS creation_time      TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS subscription_start TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_login         TIMESTAMP WITHOUT TIME ZONE;
