<?php

/**
 * @file
 * Defines menu items common to the various Drupal ftep UI modules.
 */


/**
 * Implements hook_menu().
 */
function ftep_ui_menu() {
  $items = array();

  // Top level "Store" container.
  $items['admin/ftep'] = array(
    'title' => 'Ftep',
    'description' => 'Administer your FTEP instance.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );
  $items['admin/ftep/config'] = array(
    'title' => 'Configuration',
    'description' => 'Configure settings and business rules for FTEP.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 50,
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );
  $items['admin/ftep/config/currency'] = array(
    'title' => 'Ftep Settings',
    'description' => 'Configure the F-TEP settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ftep_settings_form'),
    'access arguments' => array('configure store'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/ftep_ui.admin.inc',
  );

  return $items;
}
