datasource_defaults: &datasource_defaults
  enabled:     true

ipt: &IPT
  <<: *datasource_defaults
  parserClass: IPTResponseHandler
  endpoint: https://finder.eocloud.eu/resto/api/collections/
  # enabled: false
  source_type: external
  config:
    mode: json
    qlEndpoint: http://finder.eocloud.eu

cems: &CEMS
  <<: *datasource_defaults
  endpoint: http://opensearch-test.ceda.ac.uk/opensearch/atom
  #  enabled:     false
  parserClass: Ceda2ResponseHandler
  source_type: external
  config:
    mode: xml # or json
    itemsPerPage: 20,

    http.timeout: 10,
    http.connect_timeout: 10,
    http.concurrency: 20

    qlEndpoint: http://data.ceda.ac.uk

ftep_products: &FTEP_PROD
  <<: *datasource_defaults
  endpoint: http://ftep-resto/api/collections/ftepOutputs/search.atom
  parserClass: FtepResponseHandler
  #  enabled:     false
  source_type: internal

ftep_reference: &FTEP_REF
  <<: *datasource_defaults
  endpoint: http://ftep-resto/api/collections/ftepRefData/search.atom
  parserClass: FtepResponseHandler
  #  enabled:     false
  source_type: reference


datasources:
  ipt: *IPT
  ceda2: *CEMS
  ftep_products: *FTEP_PROD
  ftep_reference: *FTEP_REF


credentials: /var/f-tep/credentials.yml
# credentials: /tmp/credentials.yml
