#!/bin/bash
echo "++++++++++++++++++++++++++++++++++++++"
echo "Starting SECP download manager"
echo "++++++++++++++++++++++++++++++++++++++"
cd /data/cache
/home/ftep/01-install/01-scripts/secp_ftep $*
