<?php

/**
 * Implements hook_entity_info().
 */
function ftep_databasket_entity_info() {
    $info = array (
        'ftep_databasket' => array (
            'label' => t ( 'Ftep Databasket' ),
            'base table' => 'ftep_databasket',
            'entity keys' => array (
                'id' => 'idb',
                'label' => 'name'
            ),					
            'entity class' => 'FtepDatabaskets',
            'controller class' => 'FtepDatabasketsController',
            'access callback' => 'ftep_databaskets_access_callback',
            'module' => 'ftep_databasket',
            'fieldable' => false,
            'admin ui' => array (
                'path' => 'admin/ftep/databaskets',
                'file' => 'ftep_databasket.admin.inc',
                'type' => MENU_NORMAL_ITEM,
                'controller class' => 'FtepDatabasketUIController' 
            ),
        ) 
    );
    return $info;
}

/**
 * Implements hook_menu().
 */
function ftep_databasket_menu() {
	$items = array ();

	$items ['databaskets'] = array (
			'title' => 'Databaskets',
			'page callback' => 'ftep_databasket_databaskets',
			'access arguments' => array (
					'administer ftep_databasket entities'
			)
	);
	return $items;
}

/**
 * Databasket access callback.
 */
function ftep_databaskets_access_callback() {
	if (user_is_anonymous () && ! user_access ( 'administer ftep_databaskets entities' )) {
		return FALSE;
	} else {
		return TRUE;
	}
}

function ftep_databasket_databaskets() {
	$databaskets = entity_load ( 'ftep_databasket', array ( 1, 2, 3) );
	// Listing entities
	$list = entity_view ( 'ftep_databasket', $databaskets );

	$output = array ();
	if (! array_key_exists ( "ftep_databasket", $list )) {
		return $output;
	}
	foreach ( $list ['ftep_databasket'] as $databasket ) {
		$output [] = drupal_render ( $databasket );
	}

	return implode ( $output );
}

/**
 * View for /lawmakers/<lawmakers_id> page.
 */
function databaskets_view_entity($databasket) {
	$fullname = $databasket->name . ' ' . $databasket->description;
	drupal_set_title ( $fullname );
	// Path not entity.
	// $lawmakers_output = theme('lawmakers_full', array('lawmakers' => $lawmakers));
	return $lawmakers_output;
}



function ftep_databasket_permission() {
    return array(
            'administer ftep_databasket entities' => array('title'=> t("Administer Ftep Databaskets"), "description" => t("Administer Ftep Databaskets") ),
            'create ftep_databasket entities' => array('title'=> t("Create Ftep Databaskets entities"), "description" => t("Create Ftep Databaskets") ),
            'edit any ftep_databasket entity' => array('title'=> t("Edit any Ftep Databaskets"), "description" => t("Edit any Ftep Databaskets") ),
            'edit own ftep_databasket entities' => array('title'=> t("Edit own Ftep Databaskets"), "description" => t("Edit own Ftep Databaskets") ),
            'view any ftep_databasket entity' => array('title'=> t("View any Ftep Databaskets"), "description" => t("View any Ftep Databaskets") ),
            'view own ftep_databasket entities' => array('title'=> t("View own Ftep Databaskets"), "description" => t("View own Ftep Databaskets") ),
    );
}


/**
 * Lawmakers custom entity class.
 */
class FtepDatabaskets extends Entity {
	/**
	 * Override defaultUri().
	 */
	protected function defaultUri() {
		return array (
				'path' => 'databaskets/' . $this->identifier () 
		);
	}
}
